Flask_app/project/app/entity/ledger/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from wtforms import StringField,PasswordField,SubmitField,BooleanField,IntegerField #, TextAreaField
from wtforms.validators import DataRequired,length,Email,EqualTo,ValidationError
from app.Models import User,Account
import wtforms.validators as validators




class createForm(FlaskForm):
    account_debit =IntegerField('account_debit',
                           validators=[validators.InputRequired()])
    account_credited =IntegerField('account_credited',
                           validators=[validators.InputRequired()])
    amount =IntegerField('amount',
                           validators=[validators.InputRequired()])

    submit = SubmitField('Register ledger')

    def validate_cash(self,id,amount):
        check_accdeb=Account.query.filter_by(user_id=id).first()

        if amount > check_accdeb.amount:
            raise ValidationError('The amount of cash in account is not sufficient')
    
   
class editForm(FlaskForm):
    account_debit =IntegerField('account_debit',
                           validators=[validators.InputRequired()])
    account_credited =IntegerField('account_credited',
                           validators=[validators.InputRequired()])
    amount =IntegerField('amount',
                           validators=[validators.InputRequired()])

    submit = SubmitField('Modify ledger')

Flask_app/project/app/entity/ledger/routes.py
from flask import render_template, url_for,flash,redirect,request,abort,Blueprint
from app.entity.ledger.forms import createForm
from app.Models import User,Ledger,Account,Interest
from flask_login import login_user,current_user,logout_user,login_required
from app import bcrypt,db
from datetime import date,timedelta,datetime,timezone 
from dateutil import relativedelta
from sqlalchemy import or_, and_, desc,asc
import random
from app.entity.ledger.utils import time_left,reinvest,redraw





ledger =Blueprint('ledger',__name__)

@ledger.route('/create_ledger',methods=['GET','POST'])
@login_required
def create_ledger():
    form = createForm()
    if current_user.is_authenticated:
        if form.validate_on_submit():
            #account_debited=User.query.filter_by(login=form.account_debit.data).first()
            #account_credited=User.query.filter_by(login=form.account_credited.data).first()
            check_accdeb=Account.query.filter_by(number=form.account_debit.data).first()
            form.validate_cash(check_accdeb.user_id,form.amount.data)
            check_accdeb.amount-=form.amount.data
            db.session.commit()
            check_acccred=Account.query.filter_by(number=form.account_credited.data).first()
            check_acccred.amount+=form.amount.data
            db.session.commit()
            if check_accdeb.type ==2:
                ledger=Ledger(account_debited=check_accdeb.user_id,account_credited=check_acccred.user_id,Amount=form.amount.data,state_transaction='processing',type='3 Months')
                db.session.add(ledger)
                ledger.transaction_number=int(random.randrange(100000, 999999))
                db.session.commit()
                ledger.stop=ledger.date + timedelta(days=100)
                db.session.commit()
                delta= relativedelta.relativedelta(ledger.stop,ledger.date)
                ledger.time_left=delta.months + (delta.years * 12)
                db.session.commit()
            else:
                ledger=Ledger(account_debited=check_accdeb.user_id,account_credited=check_acccred.user_id,Amount=form.amount.data,state_transaction='transfer',type='transfer')
                db.session.add(ledger)
                ledger.transaction_number=int(random.randrange(100000, 999999))
                db.session.commit()

            return redirect(url_for('ledger.allledger'))

    return render_template('fabien-ui/ledger-form.html',legend="login",form=form)

@ledger.route('/all_ledger',methods=['GET','POST'])
@login_required
def allledger():
    allled=Ledger.query.all()
    return render_template('fabien-ui/allledger.html',legend="login",ledger=allled)

@ledger.route('/all_interests',methods=['GET','POST'])
@login_required
def all_interests():
    allled=Interest.query.all()
    return render_template('fabien-ui/interests.html',legend="login",interests=allled)





@ledger.route('/<id>/individual_interests',methods=['GET','POST'])
@login_required
def individual_interests(id):
    allled=Interest.query.filter_by(user_id=id).all()
    return render_template('fabien-ui/interests.html',legend="login",interests=allled)


@ledger.route('/<ledger>/<Type>/invest_redraw',methods=['GET','POST'])
@login_required
def invest_redraw(ledger,Type):
    ledgerr=Ledger.query.filter_by(id=int(ledger)).first()
    if Type == 'invest':
        reinvest(ledgerr)
        return redirect(url_for('users.dashboard'))
    if Type == 'redraw':
        redraw(ledgerr)
        return redirect(url_for('users.dashboard'))

Flask_app/project/app/entity/users/routes.py
from fileinput import filename
from flask import render_template, url_for,flash,redirect,request,abort,Blueprint
from app.entity.users.forms import LoginForm,RegistrationForm,deposit_,Setting,interest_perc,invite_,redraw_
from app.Models import User,Account,Ledger,Accounttype,Interest_percentage
from flask_login import login_user,current_user,logout_user,login_required
from app import bcrypt,db
from datetime import date,timedelta,datetime,timezone 
import random
from app.entity.ledger.utils import time_left
from app.entity.users.utils import send_pdf
from sqlalchemy import or_, and_, desc,asc
from werkzeug.utils import secure_filename
from flask import  url_for,current_app
import os




users =Blueprint('users',__name__)


@users.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        if current_user.type=='Admin':
            return redirect(url_for('users.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        name=User.query.filter_by(login=form.username.data).first()#put login
        if  name and bcrypt.check_password_hash(name.password,form.password.data):
            login_user(name,remember=form.remember.data,duration=timedelta(seconds=30)) 
            next_page=request.args.get('next')
            return redirect (next_page) if next_page else  redirect(url_for('users.dashboard'))
        else:
            print(1234567)
            flash(f'Mauvais Identifiant ou mot de passe, essayez à nouveau','danger')

    return render_template('fabien-ui/login.html',legend="login",form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))



@users.route('/sign_up',methods=['GET','POST'])
def sign_up():
    if current_user.is_authenticated:
       return redirect(url_for('users.dashboard'))
    form = RegistrationForm()
    acc=['Admin','Client','Tradefin','Tradeeco']
    for i in acc:
        db.session.add(Accounttype(type=i))
        db.session.commit()
    if form.validate_on_submit():#check user 
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=User(login=form.username.data,email=form.email.data,type=form.type.data)
        db.session.add(user)
        db.session.commit()
        user.password=hashed_password
        db.session.commit()
        num=int(random.randrange(100000, 999999))
        typo=Accounttype.query.filter_by(type=user.type).first()
        acc=Account(user_id=user.id,type=typo.id,number=num)
        db.session.add(acc)
        db.session.commit()
        flash(f'Account created you can now login','success')
        return redirect(url_for('users.login'))
    return render_template('fabien-ui/register.html',legend="sign_up",form=form)

@users.route('/<int:id>/settings_user',methods=['GET','POST'])
@login_required
def settings(id):
    if current_user.is_authenticated:
        form=Setting()
        user=User.query.filter_by(id=id).first()
        account=Account.query.filter_by(user_id=id).first()
        if form.validate_on_submit():
            user.username=form.username.data
            user.prenom=form.prenom.data
            user.adresse=form.adresse.data
            user.numero=form.numero.data
            db.session.commit()
            flash(f'Account created you can now login','success')
            return redirect(url_for('users.settings',id=id))
        #return redirect(url_for('users.main'))
        return render_template('fabien-ui/settings.html',legend="sign_up",form=form,user=user,account=account)

@users.route('/<int:id>/settings_all',methods=['GET','POST'])
@login_required
def settings_all(id):
    if current_user.is_authenticated:
        user=User.query.filter_by(id=id).first()
        account=Account.query.filter_by(user_id=id).first()
        ledgers=Ledger.query.filter(or_(Ledger.account_credited==id,Ledger.account_debited==id)).all()
        

        return render_template('fabien-ui/settings_all.html',legend="sign_up",user=user,account=account,trans=ledgers,id=id)

@users.route('/all_accounts',methods=['GET','POST'])
@login_required
def all_accounts():
    if current_user.is_authenticated:
        account=Account.query.all()
        return render_template('fabien-ui/allacounts.html',legend="sign_up",account=account)


@users.route('/<id>/deposit',methods=['GET','POST'])
@login_required
def deposit(id):
    form = deposit_()
    if form.validate_on_submit():
        check_acc=Account.query.filter_by(user_id=id).first()
        check_acc.amount+=form.amount.data
        db.session.commit()
        filename=secure_filename(form.file.data.filename)
        final=os.path.join(current_app.config['UPLOAD_FOLDER'],filename)
        form.file.data.save(final) 
        ledger=Ledger(account_credited=id,Amount=form.amount.data,state_transaction='deposit',type='deposit') #state type of transaction,list of them
        db.session.add(ledger)
        ledger.transaction_number=int(random.randrange(100000, 999999))
        db.session.commit()
        flash(f'Account created you can now login','success')
        return redirect(url_for('users.settings_all',id=id))
    return render_template('fabien-ui/add_cash.html',legend="sign_up",form=form)


@users.route('/<id>/redraw',methods=['GET','POST'])
@login_required
def redraw(id):
    form = redraw_()
    if form.validate_on_submit():
        check_acc=Account.query.filter_by(user_id=id).first()
        check_acc.amount-=form.amount.data
        db.session.commit()
        ledger=Ledger(account_debited=id,Amount=form.amount.data,state_transaction='deposit',type='deposit') #state type of transaction,list of them
        db.session.add(ledger)
        ledger.transaction_number=int(random.randrange(100000, 999999))
        db.session.commit()
        flash(f'Account created you can now login','success')
        return redirect(url_for('users.settings',id=id))
    return render_template('fabien-ui/redraw.html',legend="sign_up",form=form)



@users.route('/invite',methods=['GET','POST'])
@login_required
def invite():
    form = invite_()
    if form.validate_on_submit():
        send_pdf(form.email.data)
        flash(f'email sent','success')
        return redirect(url_for('users.settings',id=current_user.id))
    return render_template('fabien-ui/invite.html',legend="sign_up",form=form)


@users.route('/dashboard',methods=['GET','POST'])
@login_required
def dashboard():
    if current_user.type == 'Admin':
        #time_left()
        client=User.query.filter_by(type='Client').count()
        trade_fin=User.query.filter_by(type='Tradefin').count()
        trade_eco=User.query.filter_by(type='Tradeeco').count()

        Cash_all=Account.query.all()
        final=0
        
        for sum in Cash_all:
            if sum.amount !=None:
                final+=sum.amount

        allled=Ledger.query.all()

        return render_template('fabien-ui/index.html',legend="dashboard",final=final,ledger=allled,client=client,trade_fin=trade_fin,trade_eco=trade_eco)
    else:
        #time_left()
        client=User.query.filter_by(type='Client').count()
        trade_fin=User.query.filter_by(type='Tradefin').count()
        trade_eco=0

        Cash_all=Account.query.filter_by(user_id=current_user.id).all()
        final=0
        
        for sum in Cash_all:
            if sum.amount !=None:
                final+=sum.amount
        now_utc = datetime.now(timezone.utc) + timedelta(days=1)#add 1 day
        start=datetime.combine(now_utc,datetime.min.time())

        allled=Ledger.query.filter(or_(Ledger.account_credited==current_user.id,Ledger.account_debited==current_user.id)).all()

        return render_template('fabien-ui/index.html',legend="dashboard",final=final,ledger=allled,late=start,client=client,trade_fin=trade_fin,trade_eco=trade_eco)



@users.route('/modify_interests',methods=['GET','POST'])
@login_required
def modify_interest():
    acc=['Interet annuel Client','Pourcentage 3 mois','Interet apporteur'
    ,'Interet Trade','Interet annuel Trade fin','Pourcentage profit']
    for i in acc:
        db.session.add(Interest_percentage(type=i))
        db.session.commit()
    form=interest_perc()
    interests=Interest_percentage.query.order_by(asc(Interest_percentage.id)).all()
    if form.validate_on_submit():
        pourcentage3=Interest_percentage.query.filter_by(type='Pourcentage 3 mois').first()
        pourcentage3.percentages=form.pourcentage3.data
        IAC=Interest_percentage.query.filter_by(type='Interet annuel Client').first()
        IAC.percentages=form.IAC.data
        IA=Interest_percentage.query.filter_by(type='Interet apporteur').first()
        IA.percentages=form.IA.data
        IATE=Interest_percentage.query.filter_by(type='Interet Trade').first()
        IATE.percentages=form.IATE.data
        IATF=Interest_percentage.query.filter_by(type='Interet annuel Trade fin').first()
        IATF.percentages=form.IATF.data
        profit=Interest_percentage.query.filter_by(type='Pourcentage profit').first()
        profit.percentages=form.profit.data

        db.session.commit()
        return redirect(url_for('users.settings',id=current_user.id))
    return render_template('fabien-ui/modify_interests.html',legend="login",form=form,inter=interests)


@users.route('/create_user',methods=['GET','POST'])
@login_required
def create_user():
    form = RegistrationForm()
    if form.validate_on_submit():#check user 
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=User(login=form.username.data,email=form.email.data,type=form.type.data)
        db.session.add(user)
        db.session.commit()
        user.password=hashed_password
        db.session.commit()
        num=int(random.randrange(100000, 999999))
        typo=Accounttype.query.filter_by(type=user.type).first()
        acc=Account(user_id=user.id,type=typo.id,number=num)
        db.session.add(acc)
        db.session.commit()

Flask_app/project/app/templates/fabien-ui/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AdminLTE 3 | Log in</title>

<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{url_for('static', filename='plugins/fontawesome-free/css/all.min.css')}}">
<!-- icheck bootstrap -->
<link rel="stylesheet" href="{{url_for('static', filename='plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
<!-- Theme style -->
<link rel="stylesheet" href="{{url_for('static', filename='dist/css/adminlte.min.css')}}">
</head>
  <body class="login-page" style="min-height: 496.8px;">
  <div class="login-box">
    <div class="login-logo">
      <a href="../../index2.html"><b>LOGO</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
      <div class="card-body login-card-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form  method="POST">
          {{ form.hidden_tag() }}
          <div class="input-group mb-3">
           
            {% if form.username.errors %}
            <div class="invalid-feedback">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{form.username(class="form-control",placeholder="username")}}
            {% endif %}
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-envelope"></span>
              </div>
            </div>
          </div>
          <div class="input-group mb-3">

            {% if form.password.errors %}
            <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{form.password(class="form-control",placeholder="password")}}
            {% endif %}
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-lock"></span>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-8">
              <div class="icheck-primary">
                {{form.remember()}}
                {{form.remember.label()}}
              </div>
            </div>
            <!-- /.col -->
            <div class="col-4">
              {{form.submit(class="btn btn-primary btn-block")}}
            </div>
            <!-- /.col -->
          </div>
        </form>

        <div class="social-auth-links text-center mb-3">
          <p>- OR -</p>
          <a href="#" class="btn btn-block btn-danger">
            <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
          </a>
        </div>
        <!-- /.social-auth-links -->

        <p class="mb-1">
          <a href="forgot-password.html">I forgot my password</a>
        </p>
        <p class="mb-0">
          <a href="{{url_for('users.sign_up')}}" class="text-center">Register a new membership</a>
        </p>
      </div>
      <!-- /.login-card-body -->
    </div>
  </div>
  <!-- /.login-box -->

  <!-- jQuery -->
  <script src="{{url_for('static', filename='plugins/jquery/jquery.min.js')}}"></script>
  <!-- Bootstrap 4 -->
  <script src="{{url_for('static', filename='plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <!-- AdminLTE App -->
  <script src="{{url_for('static', filename='dist/js/adminlte.min.js')}}"></script>


  </body>
</html>

Flask_app/project/app/templates/fabien-ui/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | User Profile</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{url_for('static', filename='plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{url_for('static', filename='dist/css/adminlte.min.css')}}">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('users.logout')}}" role="button">
          Deconnexion
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link text-center">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
        </div>
        <div class="info">
          <a href="#" class="d-block"></a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
          <a href="{{url_for('users.dashboard')}}" class="nav-link">
            <p>
              Dashboard
            </p>
          </a>
        </li>

        {% if current_user.type == "Admin" %}
          <li class="nav-item">
            <a href="{{url_for('ledger.allledger')}}" class="nav-link">
              <i class="nav-icon text-info"></i>
              <p>Ledger</p>
            </a>
          </li>
        {%endif%}

        <li class="nav-item">
          <a href="{{url_for('users.settings',id=current_user.id)}}" class="nav-link">
            <i class="nav-icon text-info"></i>
            <p>Profile</p>
          </a>
        </li>
        {% if current_user.type == "Admin" %}
          <li class="nav-item">
            <a href="{{url_for('users.all_accounts')}}" class="nav-link">
              <i class="nav-icon text-info"></i>
              <p>All Account</p>
            </a>
          </li>
        {% endif %}

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Settings</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item active">Settings</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3">

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                </div>

                <h3 class="profile-username text-center">{{user.username}}</h3>

                <p class="text-muted text-center">{{user.type}}</p>

                {% if current_user.type != "Admin" %}
                  <ul class="list-group list-group-unbordered mb-3">
                    <li class="list-group-item">
                      <b>Total amount</b> <a class="float-right">{{account.amount}}</a>
                    </li>
                  </ul>

                  <a href="{{url_for('users.deposit',id=current_user.id)}}" class="btn btn-primary btn-block"><b>Deposit cash</b></a>
                  <a href="{{url_for('users.redraw',id=current_user.id)}}" class="btn btn-primary btn-block"><b>Redraw cash</b></a>
                  
                  {% else %}
                  <!--a href="{{url_for('users.invite')}}" class="btn btn-primary btn-block"><b>Invite Client</b></a-->

                {% endif %}
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
          <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  {% if current_user.type == "Admin" %}
                  <li class="nav-item"><a href="{{url_for('users.modify_interest')}}" class="btn btn-primary btn-block"><b>Modify Interest</b></a></li>
                  {%endif%}
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">

                  <!-- /.tab-pane -->

                  <!-- /.tab-pane --> 
                  {% if current_user.type != "Admin" %}
                  <div class="tab-pane active" id="settings">
                    <form class="form-horizontal" method="POST">
                      {{ form.hidden_tag() }} 
                      <div class="form-group row">
          
                        {{form.username.label(class="col-sm-2 col-form-label")}}

                        {% if form.username.errors %}
                        {{form.username(class="col-sm-2 col-form-label is-invalid is-small") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="col-sm-10">
                        {{form.username(class="form-control is-small",value=user.username)}}
                        </div>
                        {% endif %}   
                      </div>
                      <div class="form-group row">
                        {{form.prenom.label(class="col-sm-2 col-form-label")}}

                        {% if form.prenom.errors %}
                        {{form.prenom(class="col-sm-2 col-form-label is-invalid is-small") }}
                        <div class="invalid-feedback">
                            {% for error in form.prenom.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="col-sm-10">
                        {{form.prenom(class="form-control is-small",value=user.prenom)}}
                        </div>
                        {% endif %}
                      </div>
                      <div class="form-group row">
                        {{form.adresse.label(class="col-sm-2 col-form-label")}}

                        {% if form.adresse.errors %}
                        {{form.adresse(class="col-sm-2 col-form-label is-invalid is-small") }}
                        <div class="invalid-feedback">
                            {% for error in form.adresse.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="col-sm-10">
                        {{form.adresse(class="form-control is-small",value=user.adresse)}}
                        </div>
                        {% endif %}
                      </div>
                      <div class="form-group row">
                        {{form.numero.label(class="col-sm-2 col-form-label")}}

                        {% if form.numero.errors %}
                        {{form.numero(class="col-sm-2 col-form-label is-invalid is-small") }}
                        <div class="invalid-feedback">
                            {% for error in form.numero.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="col-sm-10">
                        {{form.numero(class="form-control is-small",value=user.numero)}}
                        </div>
                        {% endif %}
                      </div>
                      <div class="form-group row">
                        {{form.Account.label(class="col-sm-2 col-form-label")}}

                        {% if form.Account.errors %}
                        {{form.Account(class="col-sm-2 col-form-label is-invalid is-small") }}
                        <div class="invalid-feedback">
                            {% for error in form.Account.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="col-sm-10">
                        {{form.Account(class="form-control is-small",value=account.number)}}
                        </div>
                        {% endif %}
                      </div>

                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-10">
                          {{form.submit(class="btn btn-primary")}}
                        </div>
                      </div>
                    </form>
                  </div>
                  {%endif%}
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.1.0
    </div>
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{url_for('static', filename='plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{url_for('static', filename='plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{url_for('static', filename='dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{url_for('static', filename='dist/js/demo.js')}}"></script>
</body>
</html>